"""
Applet: Moon Phase (wide)
Summary: Shows current moon phase
Description: Shows phase of moon based on location.
Author: Chris Wyman
"""

# Moon Phase
#
# Copyright (c) 2022 Chris Wyman
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

load("encoding/base64.star", "base64")
load("encoding/json.star", "json")
load("math.star", "math")
load("render.star", "render")
load("schema.star", "schema")
load("time.star", "time")

#
# Default location
#

DEFAULT_LOCATION = """
{
    "lat": 47.606,
    "lng": -122.332,
    "locality": "Seattle, WA, USA",
    "timezone": "America/Los_Angeles"
}
"""

#
# Time formats used in get_schema
#

TIME_FORMATS = {
    "None": None,
    "12 hour": ("3:04", "3 04", True),
    "24 hour": ("15:04", "15 04", False),
}

#
# moon image constants
#

MOONIMG_WIDTH = 64  # Width of moon image
MOONIMG_HEIGHT = 64  # Height of moon image

#
# background MOON_IMG constants
#

X_C = MOONIMG_WIDTH / 2.0 - 0.5  # X-center of MOON_IMG in pixel coordinates, - 0.5 so it's middle of the pixel
Y_C = MOONIMG_HEIGHT / 2.0 - 0.5  # Y-center of MOON_IMG in pixel coordinates, - 0.5 so it's middle of the pixel
R = (MOONIMG_HEIGHT - 2) / 2.0  # radius of MOON_IMG in pixel coordinates, HEIGHT - 2 because of the 1 pixel margin about disc (specific to MOON_IMG)

#
# moon cycle constants
#

LUNATION = 2551443  # lunar cycle in seconds (29 days 12 hours 44 minutes 3 seconds)
REF_NEWMOON = time.parse_time("30-Apr-2022 20:28:00", format = "02-Jan-2006 15:04:05").unix

#
# geometric/graphic constants
#

SHADOW_LEVEL = 0.15
FADE_LNG = math.pi / 6  # 30 degrees in moon longitude, but fade is non-linear (see comment in percent_illuminated())
FONT = "tom-thumb"
CLOCK_PADDING = 48  # y-offset of clock in pixels

def main(config):
    location = json.decode(config.get("location", DEFAULT_LOCATION))
    latitude = float(location["lat"])
    tz = location.get("timezone")

    currtime = time.now("UTC")
    #currtime = time.parse_time("16-Sep-2022 20:17:00", format="02-Jan-2006 15:04:05")    # pick any date to debug/unit test

    currsecofmooncycle = (currtime.unix - REF_NEWMOON) % LUNATION

    moon_phase = (currsecofmooncycle / LUNATION) * 2 * math.pi
    #moon_phase = (currtime.unix % 60) / 60 * 2*math.pi    # debug/unit test with fake 60 second lunar cycle

    #print(moon_phase)

    time_format = TIME_FORMATS.get(config.get("time_format"))
    blink_time = config.bool("blink_time")

    disp_time = time.now().in_location(tz).format(time_format[0]) if time_format else None
    disp_time_blink = time.now().in_location(tz).format(time_format[1]) if time_format else None

    return render.Root(
        delay = 1000,
        child = render.Row(
            expanded = True,
            main_align = "space_evenly",
            cross_align = "left",
            children = [
                render.Stack([
                    render.Image(src = MOON_IMG),
                    # Stack below is a dynamically generated shadow mask built one pixel at a time
                    render.Stack([
                        # Each child of Stack is a row of pixels
                        render.Row([
                            # Each Row is a 1 pixel tall stack at height "y"
                            render.Padding(
                                # This element represents the mask pixel at (x, y)
                                pad = (0, y, 0, 0),
                                child = render.Image(
                                    src = getmaskpixel(x, y, moon_phase, latitude),
                                ),
                            )
                            for x in range(MOONIMG_WIDTH)
                        ])
                        for y in range(MOONIMG_HEIGHT)
                    ]),
                ]),
                # optional clock below
                render.Animation(
                    children = [
                        render.Padding(
                            pad = (0, CLOCK_PADDING, 0, 0),
                            child = render.Stack(
                                children = [
                                    render.Padding(
                                        # render extra pixels to the right to push time closer to moon
                                        pad = (3, 0, 0, 0),
                                        child = render.Text(
                                            content = disp_time,
                                            font = FONT,
                                            color = "#000",
                                        ),
                                    ),
                                    render.Padding(
                                        # faint shadow right
                                        pad = (1, 0, 0, 0),
                                        child = render.Text(
                                            content = disp_time,
                                            font = FONT,
                                            color = "#222",
                                        ),
                                    ),
                                    render.Padding(
                                        # faint shadow down
                                        pad = (0, 1, 0, 0),
                                        child = render.Text(
                                            content = disp_time,
                                            font = FONT,
                                            color = "#222",
                                        ),
                                    ),
                                    render.Padding(
                                        # medium shadow diagonal down-right
                                        pad = (1, 1, 0, 0),
                                        child = render.Text(
                                            content = disp_time,
                                            font = FONT,
                                            color = "#444",
                                        ),
                                    ),
                                    render.Text(
                                        # bright time
                                        content = disp_time,
                                        font = FONT,
                                        color = "#AAA",
                                    ),
                                ],
                            ),
                        ),
                        render.Padding(
                            pad = (0, CLOCK_PADDING, 0, 0),
                            child = render.Stack(
                                children = [
                                    render.Padding(
                                        pad = (3, 0, 0, 0),
                                        child = render.Text(
                                            content = disp_time_blink,
                                            font = FONT,
                                            color = "#000",
                                        ),
                                    ),
                                    render.Padding(
                                        pad = (1, 0, 0, 0),
                                        child = render.Text(
                                            content = disp_time_blink,
                                            font = FONT,
                                            color = "#222",
                                        ),
                                    ),
                                    render.Padding(
                                        pad = (0, 1, 0, 0),
                                        child = render.Text(
                                            content = disp_time_blink,
                                            font = FONT,
                                            color = "#222",
                                        ),
                                    ),
                                    render.Padding(
                                        pad = (1, 1, 0, 0),
                                        child = render.Text(
                                            content = disp_time_blink,
                                            font = FONT,
                                            color = "#444",
                                        ),
                                    ),
                                    render.Text(
                                        content = disp_time_blink,
                                        font = FONT,
                                        color = "#AAA",
                                    ),
                                ],
                            ),
                        ) if blink_time else None,
                    ],
                ) if time_format else None,
            ],
        ),
    )

#######
#
# return specific mask 1x1 pixel image from array sorted by alpha percentage
#
#######
def getmaskpixel(x, y, phase, latitude):
    return mask_images[select_mask_image(percent_illuminated(x, y, phase, latitude))]

#######
#
# return percent illumination of moon image based on pixel coordinates, moon phase, and user's (earth) latitude
#
#######
def percent_illuminated(x, y, phase, latitude):
    # Offset x and y so that (0, 0) is center of moon
    x -= X_C
    y -= Y_C

    # Rotate x and y by latitude so that crescents look as at user's latitude
    # (crescents look vertical at poles, horizontal at equator)
    rot = math.pi / 2 - math.radians(latitude)
    xr = x * math.cos(rot) - y * math.sin(rot)
    yr = x * math.sin(rot) + y * math.cos(rot)

    lambda_0 = phase  # lambda_0 represents lunar longitude offset in orthographic projection onto plane, in this case treating lunar longitude as moon phase, where 0 is new, pi is full

    # following equations are simplified from the inverse functions in https://en.wikipedia.org/wiki/Orthographic_map_projection, specifically phi_0 = 0 (phi_0 representing latitude tilt of moon, so phi_0 = 0 represents equator-centric view, i.e., just the crescent/gibbous view of the longitude lines)
    rho = math.sqrt(xr * xr + yr * yr)
    c = math.asin(rho / R)
    moon_lng = lambda_0 + math.atan2(xr * math.sin(c), rho * math.cos(c))

    illum = 0.0  # default

    # logic: if moon_lng < 90 or > 270, it's fully in shadow (meaning start fade at 90/270, don't center fade around those angles)
    # reason: don't want time around new moon to have extended appearance of new moon, new moon should be as close to instantaneous as possible
    # reason #2: totally ok and desirable to have day or two around full moon to change fading around edges of moon and still look basically full - moon does this in real life

    # logic: within FADE_LNG, take 4th root of delta to determine brightness
    # reason: make line between light/shadow crisp, sharp at the dark side, soften the curve towards maximum brightness, no other reason than it looked good to me and made time near full moon look good shading-wise

    if (moon_lng < math.pi / 2 or moon_lng > 3 * math.pi / 2):
        illum = SHADOW_LEVEL
    elif (moon_lng - math.pi / 2 > 0 and moon_lng - math.pi / 2 <= FADE_LNG):
        illum = SHADOW_LEVEL + math.sqrt(math.sqrt(1 - SHADOW_LEVEL) * ((moon_lng - math.pi / 2) / FADE_LNG))
    elif (3 * math.pi / 2 - moon_lng > 0 and 3 * math.pi / 2 - moon_lng <= FADE_LNG):
        illum = SHADOW_LEVEL + math.sqrt(math.sqrt(1 - SHADOW_LEVEL) * ((3 * math.pi / 2 - moon_lng) / FADE_LNG))
    elif (moon_lng > math.pi / 2 + FADE_LNG or moon_lng < 3 * math.pi / 2 - FADE_LNG):
        illum = 1.0

    return illum

#######
#
# convert illumination percentage (0 <= illumination_percent <= 1) to index into mask_images array
#
#######
def select_mask_image(illumination_percent):
    val = min(15, math.floor(math.round(illumination_percent * 16)))
    return val

#######
#
# get_schema
#
#######
def get_schema():
    return schema.Schema(
        version = "1",
        fields = [
            schema.Location(
                id = "location",
                name = "Location",
                desc = "Location for the display of date/time.",
                icon = "locationDot",
            ),
            schema.Dropdown(
                id = "time_format",
                name = "Time Format",
                desc = "The format used for the time.",
                icon = "clock",
                default = "None",
                options = [
                    schema.Option(
                        display = format,
                        value = format,
                    )
                    for format in TIME_FORMATS
                ],
            ),
            schema.Toggle(
                id = "blink_time",
                name = "Blinking Time Separator",
                desc = "Whether to blink the colon between hours and minutes.",
                icon = "asterisk",
                default = False,
            ),
        ],
    )

#######
#
# image data and array of images follows
#
#######

# Moon image is taken from NASA video at https://svs.gsfc.nasa.gov/4310, retouched by Chris Wyman
MOON_IMG = base64.decode("""RFIE4RYNBINAUAAAAAGUSSCEKIAAAACAAAAAAQAIAYAAAAFKNFY54AAAAAAXGUSHIIAK5TQ45EAAAAAEM5AU2QIAACYY6C74MECQAAAABFYEQWLTAAAAAJYAAAACOAJKBGIU6AAAD4TESRCBKR4F5NM37NZZZ5LVY3HWV37XLVUXLNJE3MZNQYHDDMLRHQDJAKQ4TEDUHLW3JHKOU762C74K76IHMOWTCQUGSEUS4Y5GTUXG2YIAQYAMAYNWYY25VS53IWVNOZLXXE5WZ7T3ZFSLCKJRQDC7M2I3J67O7N7M6OOPPHHHHTX3HJSGMPN5H225KF7OWPQ4CIM3DQP3PCMJOENR4GVUIKQWBKKU2LBODCHV6X26TKE62XVXLW62VLMY3BIFLOMF7MDL26TW2ZLV2V3HM5UCCN6UV22TOFADFGNQSMTU7WEZQ4P3CB2PTWZGFMLA5F2MUIURVBC2GUILZPUHQIVFBPV36XWPHKWZNNM2JVV3OW5WWPN3KZVT4XTSS32U5TRNX36Y7E3S5WHL47H5XZSW6UJ573JH42AJB7U3TI5GAX3Y5JEXX4WJE6W36WFULA2GFHKOY4RODMGF4NYQXSLQDTQEP54FQWBJJWPOV3KWWW6WNI2T3WV3XVO6X2R3VSLBZQ5RPVBEVM6VWZLV47O5P3YMGH6YTNX33ZMO7MSNMXJ2ICDOQDBHRY7WA7764VT6ZIMHDZ2EHAPV52XIZELREEORBR3IDXLZMYJYESJ45SARGGSUAOFYXCGPMHYYUXR3OGZV5PJU6PULIRRDUT2P46GFQMU5WVVHKQYOPDNZ47POPE5X7YMNXN3MIXJZMBWHJRH66ZX75SQ6P3YLIZIUJUGI7SGY76HWF3YWWS2VH74MCUFPL6P3SFENRMWZXRJCNLMP6WOR3IKFNGZKWNEAD5MGD73325RLDBA4SBYWOVBXFNLNTWFQS5PH5WM6PX7AKW22LHKZCH6PRSH6LACIERRJ6P73XD66SF46WLE4SCMLFKJBRDNB5ULINB5MP5QMBIVRWBQN3MPGO3JSGT7OM5ZXST4DWYQI6YJMRTBDS7F63VWOQZ6YW32R3NVW2PWXVFETVG2BL6X3FWJS36EO5P2ZUHFRNHZTPZXMYXXX5T3662FZPLGTBVJOPI5MR7WIBQOBSL64LF57MSRSGQ3W4DAECGOW63OO3V7GOBGCFGNSQSRBLE2BJUM5HE4R3BM6QH7QVCXK3TF3WPJDFKCYDK2K22WVFKKQ3ZLZ3DH37I7TSEVL4MIZR3RXRYNMKQTCW3XJB74EIKG2CQJMESUNOK4WYFZPL6ZK6PX7D43HPY4GT7TU4F2XHUL7Z6WH276UP3VVX756XP6UE3ZGF5NUVWXZMZOAS2STG2I3DYPLCXFOMBMRTVW4VYVQLGQWKX7G4VJLW25LU3DLNOV5N3NWVRLN7MSEEKQSVECQ2QRVNSAXFUQYGMFWJ6ISOVIGJJBW4KB4YL5RRTHV7AWJHTPJXQIUOBSO3LW2STHWQVWGJKDEB7OHPWAWSZLWYWJJYFTXPMXO3AA2PDQ7WMXT35JZLU6CIA7CSZGCILNF3QOR7X3H4OVO7WLM2YG56KFPPN7EMFHNTHMWS2ZUDIPD2XUJITGNGZDTKPSUYK4IMTEMFILQYAF5W4UOCDKNM6PARCSHQBPHSAZFJBCYFTXM547PJBPYBMVQL2KY3MQM5ZMT5F5TKMHRZ44K6G7HJRE5VQ5XFQDJWH6KGD45OLJEVRDCRJKFIEO6WWY3CYKBX4MEII6UWM3S6XCQ53LPLWVW3G4RWVS6372CJCZK2KFJLJYLITMVGZCJTNWTSJ5JZBDEK5E4HOXJ6GESZVS22NBUVTRXVDUCVLJCIDOJFJG3VSTTKKRLXU3VUKS5JQQ7OBBLPXMVYMJHN77BPP6TVF5PLQGQZ6AD5OHTQIDEB7OH7WA6H7ZZBPA7OXX7PBIURXW3M657X6IJP4I5Q7SKUIC6FZX4R6FWUIT6E25W7X5WYOQWKWCAKU6KD3HGFRPEJA4ID46ACMMJEEFKRAWGJWAVJF3NWTNBNLNSHXTKW6OUAQOKV2ELKJYHO32J57VQTBIIFQKJ5WX5TXFWDWS4LUP3553SFPPW7Z237XUHVU76RAH5QL3FPPXY6RGU626DRI6IJRQGY7DUOFMVUQP3OUJJ3P5NVOTN2UNIU2WA7DADWFSXISCQBDEKY5RYUXWXEMH2ZY4KKRPJFGF4E3JKAABRSSJZCTOBX6TQQI44O25DWUUEDN5K7ZIGO4YVUJF2FVBZDU2RAUDE3ALDVETKQUH7LPLTS5XUVDOZRH5X7HCSLX7H5XLIOORAF4MD547USMHNXFB4TNLG53XWIL5KTX6TBHFWIUUKRZMF4FW6XAY26YEHMRCCAWRAV2OR2SU433JWMUEJ6CDPAIAEFHJPDJBWTJ2CO5DFECURB574J3UXWHNL2VVLNIE6QDX4PBMULUM3HJPXODVK4HEDWHVWE7VOGMYFB4T5CCMUQOHEHQI5G6J3EJQSJ5R5Q6TOZHLX36ZU3JOR5XLG2HIAKSPXT6RJSGODMJMDGNJGBVDXUDHIM2DQZBAUJS6KZKNKGIWYTQEFSUAPSTQK4GYP7RER7FA5KGUTPNSVGWZIUZSH54QZCU6WVCUWV2D4GD624HDS4HGTO3CDKFPVSWNRQZFCS2MC2MLBOF5522TVI2O2BIGA4UQEDRE6STGOTWYKH42EYUT4SVGGDUF56HB2HBS377WNNN7P3X25W524B2ITB7MPQGFFNDADPWPN5CF7ENXFBYBT3SX2B63G324VF7UOEWUN7K3P7ZCCNABH4ZRSDGDW6WYGKP3LVHNOULJZLYJRI5AFFSHKOQ4U6U7HGZUYFCRNVOKELZKQHCBO6VKUGW3BLTMOTRBV6MNBZKBUHYMRVSOITQ7DHJ3QR5KICS2OFYUT63GV5QQJKQSRMJH4535D2BYUIVWJAXSKE5UNJ2OOPKLFHCNDETA6MIACIKBRAQKKGQLERVTWRP6N4VI6W6O5CQILF7ZDKLROEA3WD4EYR2TWIZUVIIU5EQHHQFP3YEYUWTL5NV6UDTK6LXEWSMPXZMBDUO4H4Q7I5HUPYY3DMNLJBZQQ4KWSBPMAEO6OPAFEYVJ2AADCNXF5DW2KB5JGE3DM2QXL442JZZKGL6WA7IWQO4ESH546YUN3M7VKBH3AM4DXCAWEWL5GZV4GUX7GAYJOIBO4MEMZNRDOVDISU6KJAQZSWS6YELDFSG6N6U3YME4WKVYOZCUVMF7E4SYJZY4RSM3AQCK55XLLMRY23UIHLA4UMYRFGNAANAFRBNJL7FN3LZMFEWSUXUWPQVXOAPFAAXJAYK2IIQOX4IAN7V633Q7XOMJFCL577KVO6Z3PGGG3RNMGEVZQ6TEOXPIW3QI6ZBBHMOZ3NUNZ7HGURE4JKJFJUJA7IKJ33W3EQ3C37W6BYAVR4EKFK6UHHKWC7H62XZ66GIVLEEV6SNJGYVMNJRUBFRGD4NZTFNBFXMZBSSSK5NIH3NOTTH47HAAII4FOO2TWK7LS4S5KEOB5HOTWWRJMSXLLS5C5ZJY3GULXUNU2YIGL7LLKNIZMHBD5ITSIEQ6XR2REU3PFVNY4QBU2OTY4K4CJGXWPPO5SDP3IIQSFMKAUFWJ6756OBQRSSTMQJ5432YRLZNVTEMTQJVNSKSWX6ZKODAQQEPTUACRDRHVZFQL6UBPKRSEUPKDJ4NU6KQ4WXK66WOOW3QN4XRPHN2D37WLUHAVISLPOUIMEGC4CHEGZOWDXSNBKX3IN45QV6WZIRMZKMVEHKSIJDW2S3INKF3D6RM4EZD4CWX72UKPXO365JKASCRP75HHZ3PPZUFRKQACAKTAHRX6EQSNKAUO3SLTWXSWPTLVH2Q7VDYKMJ5PZ5DELBPSDYRCJIYTSOI6ZPT72462LM4ACKGQW6QE46A7FOYKSWRX76AJPWNKJNOMZ5O3L4UPROKFQFZD3FT2D6TIT6KME5EKUQACPX6YLJK6ZMK6FXUQJJBJG4DXFKRWXLFPF3MNFUUSUO3KDBCQ4O6H36JS5OFVMAAA7VZWJMPDZJS2SLC5DQULMRG4WC4OEJ54223DPX54V4CSQ5JGKSQL642SBHMRZOV2MLHEXHESHCOUV6DJNHL6OB5YSGK54E6ABXQX2B2GE3BZYHM56XIQH6JFAQKLMUIWJIIEDMM5JN36BAN2I2MIFYEI2PBLBXAMQO3SUVJFBP3KXR2RBO6C7RKHTCG3KCGBANKPTCJA6LSVGSI3GIV5OXTT6RQVYWOHX2JSAUKLDWIBG7CODQ5WUNM2EYW5N236EGIWQCI55PN7KQJI4GPKNLGF2AAYE5VTKHZLVDNUNHRYDMVFGEROKCD2ABQNE4CFBHWAUXFEFSLINB2FL3C46GIV4WS4C7S5BVJE2TSZCHB7WVMJGLZMYXACI5WTAOFAUWXEBIOMQVINPG2VVYK3NDXSXSVNIEJSZW4XIXTCFHPWQN4MVLCEMTQGQDAQWQIBGU4J4ULVKQ6UFXB4ILZJJGB27BABDQDAQLZHFGVN55RQIOKAYX43SKESKFQT52R6D4T3HKB2HDS7HOOBH2QPHNDE5BGEXIB5P5FCSALCHADFV7DQNJFGIWDPQHUGT76MQNLZL46ETRPFRUGEOCOCYDYAUNV5ZLHORJYJJ5INZXNSZVF43GRFVICBYJRKRFBD44QME4GYNFYFQDQ6OBRZMBL7BA22HRXJLMUQIJXADSL25XHRGTYAOPD6MYI2WKTHEEPGAROJELBEBN3P43TMTMNUO6ZBKV2OMZWVGOI2ZPT6I6C6B3OXHRB7QOJAV7P5S3G6OHACBG4QA5GIVNKOEWGKNNLNNFV3RZVYCHGZ3H42WSUJTNBJ2AJYN7EODFZXVP2PJ4WSUPTU42F46LTDEI2I25WXQ6CIEQ5ONAMBCFSLVTAPW5IIHDEXBKFM4TKXJT4ZUEMGRUCQKT5IU5UJDLEE3UVJZ5TFLL57BSKIB3OPXSARKNWVNCJDOIKJBIQENTSIXPGH434BZFKIPUDBZIYKJLEBYUOSRUHQJVNPMW2JZJHJEDNNSYUA2SSD5D2JYJRP3WB2BOB6I3DFZPX6T5NO5WKAH7EMRNI6D3IGXLEGLZOVZ4VXEPKUTIYGXVZPPLFD4I7DS6LJPPOXJGORMOT76U2WZC3TJPZOQSYWUUHZU2SGVELJK4VK2DADRHTVLL35GBUQZLZCRS7JCHAYD7Z3R7NL4IQN7M7S4SHDJW3E4PRGSRCRAAITXAETWSULCYOLJJ2IA6CBGECS4DIKBEERS6UQJYZRX24UMOOC35C2CIPMRCAPG73UPZJOFMVUQQ4MIGTDGMZODMG5KNSFOZBECEA623ADQRO36PXNPGHBGU5T4B6NAFDMFWV2QN6EUPVEK5MOL76XVFP3NNRLXQQQJ2X37D647OHSXTUCA6RM3CY5NCH2TA4HXV5IJ54NRWPPXXGZWO5OCRDMLJYVE4FU2BTPDZFAI7N75QISZLSURSFIWO36EB6STEK2S4T4J5DVFZWO3VZY6JOEIAGUCHL4U3HUTJ3AH6UZ2T7PWD64D4KOUDEPB3C7H3KWPEI6OL22OS4YXVH7FRN4ZXHG455FG6U2O53VP2VNV3PXEIJ6DHZ3QMM6BXXFIACREGC2OVZBZSAWUVP5QW56DM3KR3EQVW5NEJBK7NQCTC5KQ5Q2H5Y6XZ3XTT5K72VZMVONVWDQLBCG6KMSUM7T4KMDUORSMISWKYGCDUOFGH3PG3KNMUDRTSFRPCNCSFPFO7JFV7MBGQ3TTGCDIMVE2KTWIDAMR5NH5A4HFQRB5IJI2YHMOZBUF3M2UFI46Y4PQRC2IK233UXPJVSRQ45Y6P2BY6KMLCGSBMK7WCDWSH34L2X45EG36DNU3OWXUMWM7EFFJJROENMVJT4GMWLCBF2PT732IZ5INFJLYDPMTS2QEL3MHKWB5LU7GEU3VLXYREYMN3WFKXHWEJFCQ27Z7TIRTFYSYU2OQS2CNFIWKKFK2L4622VV5MFAKFLVN236MZTM3IXRVEER2IUUYK6NNAWWDGNWGMQSSDMWVDVFZ5YC3NSDF6EDT2A75AZSW25DUKTXUS7UDJQMQ34KSTFACTULHJYQR7WPC6KBJQXXJUIPGKVSSXMVZXIRR6UHNTAW6UNWNOFFYTYGZKBRN7TYIHJ6OJXU6EWK5QTY5HCWYC6MAMDIGXRAKPRQYFOIKDQA2J6X4VC2EQLUOWT57EDDVGZ75M2EOBORJ4UUGLLSNFFLUK3GMBP5RKYMO5NJ3HRGPDBRTARLINBUEJVYM3GUDUPOKLDQNA3NBVASWFI3CUA7BXPRXTSDOQQRRA2ZYFGHFOMMVO7RYEWSX3RNEEM5NVS7U5SGLLGY524XSQVECJJNOFUEZXE46XI26ENB4GYTRSDAJAAY6EDXXCQSQL3NM5RDYDVI3FOFYUSF5H5ZDQ2IMNNFPJWK3RKTXPJGH6EJ64STSWQLNSLY5RRHYQTPUDIXHQ7KFMV2EPIRCWHGRKBESJCUQOFNNDT4K7SMBCQUE7PDCORNSIPHCGREOSYORIQHAAVUYFQKSX7ZVKS54ISCBTK6VDM2T6N73M4HHAWJPGRAVLDUE5SVWVFGI5XYIGJ2PTQ5XY2GKEPBMIBOFCRCD6KA5HCCTICAYLQNVAKUAADMJOUWJUY4WCQYX4Q4HV53APCUY4USOIGWJBH3MCBJKGWQUMQOKSRSE2NRGMCBNV5OOKFSZITUYBKVHCRZAZ7GRCHFKR3OMBN4A67OCYXMSPQ6UE6PDR25VDWKJF354X6SCBMMHTZZIFQING5HZQS6UOVG45CK5OMFYWFUWAI6DOMJ64ZYF4F6RAA23YDGU6YOAACZDHAMGNOC2CSKOEERYRAMUUJEGSPLQQD76I2N2PRJJPY3VQOKLR2IKXJOBEENRSHMTHJGOUXCRUGU2CJTMKDNCCK4EYQBSEU6E3M5G6V5IANQV5CUFHTDF5NGVBEM2D4DYPFST6UYHU5WP7VGBEAGUJECFJHWMLRIFYFP7WFSM3ERT2A3FGWROGQMHW3SXXG46TGY7BCND66PRXFRIYBZRAIKNA24UOVFJYEEAZWEXIX3VKF2CMB7FVUBBDFCI6TTDYSCSQSZUFZQRTDEU6V2JEA6RAXOO2KKKUXUSGZ33GQBD7SKZA2REIJJBERIONOB3ZQ2VDIIMJOMAPZDFDAX6B3QQKZ542OTS7CYK5WPW5OJT4NJBMVGSLE6SVCXXUQDQLJNFVAHZAZ5YCSCBWBLYDDRCJX634KWFYUC7XVOMYAFUIPUAECGUZXARILRRD4CF2DQZKN6WDS7ERUTWTONZS4USOQ7A2UJ4VHX4QCJYVMVC3T5NWPIRDIU763EDEZOKBC3LA7NA2LKIDAROR5WNYU4NNIB3CJPUTWGJUJGQQBRNZUXZXDXCCRI6CR4IAZFMO6MHEOXDF5JARVMKMMRXEIGH2NBHOFJQYZSFZD33SB6RRRIJPA6IKKGRJRAGFHAREKSCNE234EYGG3Z4TDLXWSG4MBEICYPDVK52IDMLDMJ4BF3K2CJ6VI34N2EPBVSWC5KQ5UPQOKVM5BNTMHYKBCZHT6SRZ5LXUG76ITXSQZFH7E7XJHEWWUUESTAXRHGNAMMKAEYHJOCWT3ZFHG26REMFRSYZAIFSF6BIQPJFIUP6J4NX6OFJVJ56CXST3A6PENVEEUDIVATWAQRHI4VHAASIAXHQPKAIBRSRBQKAEOQURMZKJIOTYTW3LTJYSKKRQVRESJMMLFP4LJVHU6OZK6Z32IILU6DZNVGUYXHT6OJH5FCNDQOJDQ2JEPEJJ22CX3NTFKEORJKMJIQSJWECLUUG2LTA5VLXOQ45OI2UROKOI3S6SUBOOEAACBGHKOT4356TMPF2Z4I4YUZHURTVRZPJ3RTR4OVNHRLB3FJBSQW7U3F2GYXEIGQAPMOMC7ENTQS277FOBWP6TQUUYEWQSH2YK47PA7AMALFX374YU5HEWREEYOAGEVQR3WKEVQZAJIQFBJ6UQKAK3TNSZYVWREX7PKS2KFABC74UX3RSEDUROZYRMECA5CBDKAIW3BFKYMWCBKHU3KD75BQXEDDYEXUIG3WEEWYQVSP772SXC2LEIPPX3HDT5Y3XK3YWITQNBXVIWHT4YKQS2ANE7YOM2PZITDIYW42BYQIVEF6BIJO2O3AGFEB2YGPKGA6E32Z3IPHBCODDJBGRONZNPKBCZN6SPGYIEKBY2TS7JFG7ZTMHMPIPQLEH63TYWRXUU3V2ZWSMIGCO5OVCUMMOUO6M4SOQNTK2U7Q6RANSHEOO5TCWLMVOJVFEFWAYZ37GWQXKO57PQIYLBMROO2EHPHOIK6JO2EPVNQYTA3U7ULW6IJSRCOMUEBS2MLXRAPTMQN4GE6AQYTNLYGMXEQ4SKJUSLSKM7J3DNNNAGY2ZCFAZVF6C6LRNLJLMOQSCIQMYRURS6P63UUQCUORYENY3M2IKSA2UCZUZJZBAIUYS5B3UQWYI5IV3WYDLPLF2YEQCHOF5SZYGI4U3BUYUKGWBBH2AIOUVKQSE7IJVNVAV3Z4PP73HG5NNXLDLWV67O5BWAULAIQR4HYBDFEH3G2PAI4MWCUSDBPEYBATH726BTELXQFXWTIFIDI76F2ORSENKXKEL4N37EHTDREKN2XSWSETTESDMRCGZXG5IJE5L3GGIC4YRIVNTQUJUAFY5UQ7TNI3LO2NG32ZIPLYXITUORLEWCVLRRSCI35SJJKBE554ZO2C7ERBZ63ASWEPRRKGEOBEBKJJOX6XMTSHBLPZJZ33PNJLXXWZQHNUQAN44HCPICBFWVFUS3IWM4ICKTSAFJQNLSBICCL7OSCARBT72PIYCFB6YWANKRYQ4OIII5GE3LOYACEJMY3WBST3JDIPD6YBZSU4TNRRASROSDOMJPRDYZH2IUR6W7NM2LJRSJOXWZB23QRYQ6KZKZEVMNMZT6RHCGKBIPDGX25L72EN4TD3I5MNECGJWCCHW5LGQOKD4ERDIG47GSGDZLLYDV2KKRQ66M4VVOKMDZTTINBSGNX3AMHO5RQ7YFMVO2KLFGA2FL7HQRDFJBYHS2MLPMPIECRBQDISNAWZAQNZYFZD5I7XHHMWDZEMEKA4GW647KTKKNRQIREHDG5QOKSA6UCANI4AIVDYPSXTL3NQ64RWJDDNF5TQB3OJ3NHATE6JW4BHGYCAUHST7FFFZ6N4EVSVG554FN57EXZ2X2ODRP2GY7336KV7ULPIBI4N3BETTBAZHIL2ATZPSVLP3OY3OL6X2XTDJ6NCJO4WJSSDI2UK6TAE2FWFIWOEBJTUBELSPMNHZZC6TS4Q66CQ67WIQEM2TIQ5DWES7QKZ5KRNP3RVJZ3GWFI5EE5DDHLTDMRHS3F4PZAWTW7XUXA67Z4BD3JHVPV5EBEFW5U7THRRF5SBC6JYIRKCQ2HX5V23PLTYPSBGLCHAC6TDDZ47P5GHH6XYNRBB4S522RYYQ7CIJ7C6LJPLLUWN2FBQQQCOUDQJRM3TIHLB6VRBIFSEATYTBKETBCPADJITWO65JJK2DWOOKOVUKK2NGIAABZQDTH7I2QSVOKKCKPRVWAVN7TSIDSULIPJEEHSHG7VGVPXFEB5XDUKENYFYC2NGKTZDUSALJOZCHK54OKUQVMDHV667R3O3KT7NRDQASZHWLPXUZLX2YJU4VJV4HGQSWZEAURDCZFOVY3HIPBMEMFA5LHE6DSQQWN4PARZMRW53663TIU3EGW2MZXGKACUKNA3BREBSVHAMKGMV2V54PZIMTQPUTF7UO6UM5VPQOJRK4UEVZ2DYC2AJ3SPGPBHTIF57F4R2CNL7XSXP7VDYZYEUOGNMQEMCNH34DA3NGT5WJP3QS7WXCHHPXHMDOEGAMLHH4J6PHQQVMVRUARLQMHPQIDYWAUDBZ3EQFFMBUKIAITOH6XISIK65L7OTSBMMHE4MO4H5YZUDRDB3Y3OOHRAB7WXKP4SWTAUCSMTBYUOBNGCJDKYLRKJFBDY6GMZ62XYUOZRF6DRKEQQ4JFOKBDM7JAQKETAFIEYIQUIVTYOI2SLWBGYXBAGCBX2IDAKMHSPXXRULT3WD35O3RZADCUNBRWHYZ2YTGQSUCXMT4RO4UMCCSD5HS4RPK7V7VDMOHBQHI6CUM3TGMXL6MZZ5TH3ACAKRIZFQ2CJVJZUPDU5GIE33U7WGYYSSAYH7ULSCNIMEEFCARBECUC7J3OZAU2MRUMYQYQS5IGJA3CI52JAXXDIFMNNWITOKCEBKABBDCNPEMUJMCLLYVBRJCLGDUFXN7SN67WKP7Z5HHQFGTPV3PHGADKLKDD2ITIZWQABCKTJ74YIRSUNBKNKZYECNQGZH7XTD5ICKOBYWSWJHY22LQODONDYZHXVGYMIZYNZKB3WVAXLAYYHEIWFCI6XHHHGPKBYUYCMK4MQNALBFEJM4SYLAJ2BUI55QSZ3LSJN74H3BZ6UN5YOOEPDJC6LCHMSCJRPOZAQHOBM4F7EN7ML6PH3XQV4ED5P3RZABAIEKPDLA5HU7YUDABYGRWTECRBPA2IDLS46CTNGSNAJ3YQDVJRQZYVBMCVOYH5KKBPCSNQL7RUPOOIUKX4APGKOBBIGCSG6I2RR6CPQRQHT6MCMNJKTLO6LER3OSOJDR6B6RI6YDLPGFNFGCBXTPHTSUDHA7CFPTKOW4MGFMVKJOPMO62ZNF7H5XVN762PPL57EHB5ELB6GXTM6FQBCBSAIOUDNRIO4WCIUMGLLKKQL5OHLXETEQMYYZLNRRPFQFEOMBBDQ2ATYDOPLRNV6MLIPVDONFJ7TTGXNZCIBVXCQQ2EC3H6BEDYTRDQLPPVSSYGRAMASOB4ABU6MATIQUZFZ3QA2HCF57BBTHLPNBQ47W7ORTFZVPH37INPPY3XX3XST665OVNAPMNI66XV34QGE7EGQIU42HTOWKR2RTCDDA42B2KDMSYPJUH3E7PFFR6H2XM62DROEEHTTXRJR5VZOLRAEM4BQECTTTXOOGATMKRSQLHZABQ3EDJIKKYK26AI52H54ABZKHRCN67IPL7GGJ4YD35CFZVFG7SND63STL32JF7PPSYV7PTK6P7HKTTXN2VWB5QZCN6WUT5E4PTRZQG2KSLAIBX2QK6KKCQRQIFB4AQCQ6QBEJBJI2CLJABETTY7MBIQWBIOHDJV6B6PAZYC5UPBCVBZYJKOIOJSHCOI46PTXCIGGXKH5KN6QJAGN6SOPKFT2IOEXDXWLHLSLWIOOVZ2UUOHLSADSL77LLX7MYVGVSR7NR62QASZSWF7TJJEHJ7OZKHCUBNK7MVXFQYMIB4BFBGAXD3AQO2K7PEPPNBD2U3XZBVZ3QRRCBNAGN6WO3MDQ2PEQAG67XRAGMID2OBTCE6SAFSIDABIWKLF4X2RLIKOLSUUAATDHAB42DYHYEEBUUVKHUHAG675IHF4KBD357VN7NJK23X6GUCYC65X6ZLMJSSHTWOGJGGJZOJZC3CGDIQ4HS34GQ2VKCD2KLTMDSSQKGYV4DIOL2B4RVD7B4BEJKAARCCMWJNVZQ6IRP5Y6IFVNJMGTY4ICSRV7VRYELXFZSY5GI6AIUJ5TBY4S37IHM2GMVAHU3AYTMQWUT3C4XF4CXW6ID5MH3VABVX4YORMZTETB7DGKLH6A6EMRDBKQU3IOK4SBW7FCDEDAEIE2OEESMDBS65MI3Y4QYNAQF3VIYANENE7QUYP7LWTP4AKZYIABBFRT5FFNEKGOQAPHTAGIDHF7ZOLNIVLNPJZ5ZKCEJOWU5NV2FLXHUX3C4RHY2ZO7SABVWK3K5L2LRBOHRPQ4L7RYDQECT2O2DCQQC5BQWO6Q22BRLGA4LYYHCY557DFJX4U4KWI5HIGB4AHPHKEARYTHU6LLNO7ZBUZQ7QHAEE5AB4NGNJR4MDXJFGKXOVVDXDZVGQ35GIBXV2PDIZ57O2G5COA57WN4CVQ57MAALJHY27X32GXHYRGAAODYRAAHB2XYULCTRSUOIEY33FFJZOGKUXVTSG7ENQPOERGKEBWLJUHJUAVRO3TVARXDMRHACQ3ARDDHMPEL2NFB43VTBN43T34AHFXCTPJGEZTG3FOXR3N7724FRX7ADVI556H2JAGWFIVNL47H3XQI6HQYF72IQ6UVMCQ4RRAUAQS2J2IQQH3SMQXOG2OO2PA3CREBGWCM7P5WK7WPCKI6X45OPBCIPYZSBJBQ2725UYMQXURYFGA5BVAH6F6G7IJUECTD7JXX7ZTZ676RZ76YE7IR25ECF3J6SYNNUGRUH66EP75XQ6HJ6VVARHPBZMJRMRUIGVDUMZOFFQZQVD4XGUQGR3WQKU3RSZHTTE4F4IPDISDHXHDCGM435LN2BQIBEOHNCOCRZI7ESFQXCRCX47DWHLOMXXZXMHGMP5PDF3OIAIW7B5ELM7YZ27PHDB4PPTVBHY7OKXYDZUGGAHVHY2AM3ZZYR6ZJAN5BAN33OKLATD6645EZUEC72QI2KT3DQIKCAIYVRGXADGBQX4RNP75UV67XO67WOM3QG637VOWZ77ODXY4DND6OLBJ477KBJ3PP3ATP23IT3RQUTVYBQLIAQGSIXM52BSTAT37PJ4NILS5DFUCNJMBGZC7XCDC7AXVHF5HHX76WJZ7WD777HU7POMPVJJX7SEDWYLOIGCFG237HZ5PPLE5HZ2MH54OJZ4CWML5YAEHCBFSASXB24IFHEXEIKNY2LOPTQCCB24T6PLCV27PPG45H37YPPLS5GJI73J75DOH4KQO7DQYH7LJSB4L7CCG2QH65HXVGQE757FQCGR44UEAHVNLFPF5NUNZWVEO63WN3HOPDZY5DJVWZX7A7N7QHSS3XYCNJIAAAAAASKFJZCK4QTAQI======""")

BLACK_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBg+AcAAQMA/60lLy8AAAAASUVORK5CYII=""")
DARK01_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBgeAEAAO0A6Rx+CV4AAAAASUVORK5CYII=""")
DARK02_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBguA0AAOAA3PnKAd4AAAAASUVORK5CYII=""")
DARK03_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBgOAcAANMAz3LU0l0AAAAASUVORK5CYII=""")
DARK04_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBg2A8AAMQAwBTxXkMAAAAASUVORK5CYII=""")
DARK05_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBg2AQAALcAs+GNWA8AAAAASUVORK5CYII=""")
DARK06_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBgWAoAAKoApiqyB0UAAAAASUVORK5CYII=""")
DARK07_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBgmAEAAJ0AmRsqtiUAAAAASUVORK5CYII=""")
DARK08_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBg6AQAAI4Aij1Rq0oAAAAASUVORK5CYII=""")
DARK09_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBgqAEAAIEAfQESbwIAAAAASUVORK5CYII=""")
DARK10_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBgyAcAAHQAcJFDDXwAAAAASUVORK5CYII=""")
DARK11_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBgSAIAAGcAY9NGKsoAAAAASUVORK5CYII=""")
DARK12_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBgCAYAAFgAVJtWGgcAAAAASUVORK5CYII=""")
DARK13_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBgMAUAADoANm6hnKYAAAAASUVORK5CYII=""")
DARK14_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjYGBgEAcAABwAGAzCM6wAAAAASUVORK5CYII=""")
CLEAR_PIXEL = base64.decode("""iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAAtJREFUGFdjYAACAAAFAAGq1chRAAAAAElFTkSuQmCC""")

#######
#
# array of 1x1 pixel images from opaque black to transparent black in equal transparency jumps
#
#######
mask_images = [
    BLACK_PIXEL,
    DARK01_PIXEL,
    DARK02_PIXEL,
    DARK03_PIXEL,
    DARK04_PIXEL,
    DARK05_PIXEL,
    DARK06_PIXEL,
    DARK07_PIXEL,
    DARK08_PIXEL,
    DARK09_PIXEL,
    DARK10_PIXEL,
    DARK11_PIXEL,
    DARK12_PIXEL,
    DARK13_PIXEL,
    DARK14_PIXEL,
    CLEAR_PIXEL,
]
